apiVersion: v1
kind: PersistentVolume            
metadata:
  name: sonar-pv-data
spec: 
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/data"