apiVersion: apps/v1
kind: Deployment
metadata:
  name: drive
  labels:
    app: drive
spec:
  selector:
    matchLabels:
      app: drive
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drive
    spec:
      containers:
      - name: drive
        image: plusultra2020/drive
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          protocol: TCP