apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 31000
      protocol: TCP
    - name: slave
      port: 50000
      nodePort: 31001
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31002
  selector:
    app: jenkins